In [ ]:
mid_scores = [10, 20, 30]
final_scores = [70, 80, 90]
total = mid_scores + final_scores
total

[10, 20, 30, 70, 80, 90]

In [ ]:
double=mid_scores * 2
double

[10, 20, 30, 10, 20, 30]

In [ ]:
import numpy as np
mid_scores = np.array([10, 20, 30])
final_scores = np.array([70, 80, 90])
total = mid_scores+final_scores
print(total)

[ 80 100 120]


In [ ]:
a=np.array(range(1, 11))
b=np.array(range(10, 101, 10))
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 11  22  33  44  55  66  77  88  99 110]
[ -9 -18 -27 -36 -45 -54 -63 -72 -81 -90]
[  10   40   90  160  250  360  490  640  810 1000]
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]


In [ ]:
a=np.array([1, 2, 3])

In [ ]:
a.shape #형태

(3,)

In [ ]:
a.ndim #차원

1

In [ ]:
a.dtype #자료형

dtype('int64')

In [ ]:
a.itemsize #실제 메모리 크기

8

In [ ]:
a.size #객체의 전체크기

3

In [ ]:
# 넘파이 배열의 연산
import numpy as np
salary = [220, 250,230]
salary = np.array([220, 250, 230])
salary = salary + 100
print(salary)

salary = salary*2
print(salary)

salary = np.array([220, 250, 230])
salary = salary * 2.1
print(salary)

[320 350 330]
[640 700 660]
[462. 525. 483.]


In [ ]:
# 여러 사람의 BMI 빠르고 간편하게 계산하기
import numpy as np

heights = [1.83, 1.76, 1.69, 1.86, 1.77, 1.73]
weights = [86, 74, 59, 95, 80, 68]

np_heights = np.array(heights)
np_weights = np.array(weights)

bmi = np_weights/(np_heights**2)
print('대상자들의 키:', np_heights)
print('대상자들의 몸무게:', np_weights)
print('대상자들의 BMI')
print(bmi)

대상자들의 키: [1.83 1.76 1.69 1.86 1.77 1.73]
대상자들의 몸무게: [86 74 59 95 80 68]
대상자들의 BMI
[25.68007405 23.88946281 20.65754    27.45982194 25.53544639 22.72043837]


In [ ]:
# 넘파이에서의 인덱싱과 슬라이싱
scores = [88, 72, 93, 94, 89, 78, 99]
np_scores = np.array(scores)
# scores[1:4] # 슬라이싱, 요소 집합 출력
# scores[2] # 인덱싱, 특정한 요소 출력
# scores[-3:-1] # 음수 인덱스 사용
scores[1:-2] # 음수, 양수 인덱스 섞어 사용

[72, 93, 94, 89]

In [ ]:
# 논리적인 인덱싱 : 어떤 조건을 주고 배열에서 원하는 값 구하기
ages = np.array([18, 19, 25, 30, 28])
y = ages > 20 # 20살 이상인 사람만 고르기
print(y)

[False False  True  True  True]


In [ ]:
ages[ages > 20]

array([25, 30, 28])

In [ ]:
# 난수 생성
np.random.rand(5)
np.random.rand(5,3) # 난수로 이루어진 2차원 배열
a = 10
b = 20
b-a * np.random.rand(5) + a
np.random.randint(1, 11, size=(4,7) ) #1부터 (11- 1)=10 사이

array([[2, 2, 4, 8, 7, 9, 8],
       [8, 4, 5, 4, 8, 8, 7],
       [4, 3, 1, 5, 5, 5, 5],
       [8, 4, 8, 1, 1, 6, 2]])